"""source discovery: discovery_json, last_reviewed_at

Revision ID: 67b87036cf8c
Revises: d114bd24c71d
Create Date: 2026-08-25 07:19:47.485142

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '67b87036cf8c'
down_revision: Union[str, Sequence[str], None] = 'd114bd24c71d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sources', sa.Column('discovery_json', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False, server_default=sa.text("'{}'::jsonb")))
    op.add_column('sources', sa.Column('last_reviewed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sources', 'last_reviewed_at')
    op.drop_column('sources', 'discovery_json')
    # ### end Alembic commands ###
