"""signal layer: signals, signal_evidence, content_items.signals_processed_at

Revision ID: d114bd24c71d
Revises: d0d0e0bfa6e8
Create Date: 2026-08-24 20:47:56.769662

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd114bd24c71d'
down_revision: Union[str, Sequence[str], None] = 'd0d0e0bfa6e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('signals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('merged_into_id', sa.Integer(), nullable=True),
    sa.Column('lifecycle_stage', sa.String(length=30), nullable=False),
    sa.Column('first_detected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_evidence_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cities', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('countries', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('categories', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('evidence_count', sa.Integer(), nullable=False),
    sa.Column('source_count', sa.Integer(), nullable=False),
    sa.Column('cultural_origin_score', sa.SmallInteger(), nullable=True),
    sa.Column('editorial_momentum_score', sa.SmallInteger(), nullable=True),
    sa.Column('urban_adoption_score', sa.SmallInteger(), nullable=True),
    sa.Column('meme_recognition_score', sa.SmallInteger(), nullable=True),
    sa.Column('creator_adoption_score', sa.SmallInteger(), nullable=True),
    sa.Column('commercial_evidence_score', sa.SmallInteger(), nullable=True),
    sa.Column('saturation_risk_score', sa.SmallInteger(), nullable=True),
    sa.Column('longevity_score', sa.SmallInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['merged_into_id'], ['signals.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('signal_evidence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('signal_id', sa.Integer(), nullable=False),
    sa.Column('content_item_id', sa.Integer(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['content_item_id'], ['content_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['signal_id'], ['signals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('signal_id', 'content_item_id', name='uq_signal_evidence')
    )
    op.create_index(op.f('ix_signal_evidence_content_item_id'), 'signal_evidence', ['content_item_id'], unique=False)
    op.create_index(op.f('ix_signal_evidence_signal_id'), 'signal_evidence', ['signal_id'], unique=False)
    op.add_column('content_items', sa.Column('signals_processed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('content_items', 'signals_processed_at')
    op.drop_index(op.f('ix_signal_evidence_signal_id'), table_name='signal_evidence')
    op.drop_index(op.f('ix_signal_evidence_content_item_id'), table_name='signal_evidence')
    op.drop_table('signal_evidence')
    op.drop_table('signals')
    # ### end Alembic commands ###
