"""weekly reports table

Revision ID: e326d50dae29
Revises: 67b87036cf8c
Create Date: 2026-08-25 17:28:14.266824

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e326d50dae29'
down_revision: Union[str, Sequence[str], None] = '67b87036cf8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weekly_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('iso_week', sa.String(length=10), nullable=False),
    sa.Column('content_markdown', sa.Text(), nullable=False),
    sa.Column('sources_covered', sa.Integer(), nullable=False),
    sa.Column('items_covered', sa.Integer(), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('iso_week')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('weekly_reports')
    # ### end Alembic commands ###
